### ISSUE TITLE
Exit without arguments

### ISSUE THREAD

**Issue by Potato1682** [psac-serve/cli#5]
exitコマンドに引数を渡していない場合はコードを0として終了させる方が良いと思われます。

**Comment by PeyaPeyaPeyang** [comment]
このコミットに修正、テストされました。

**Comment by Potato1682** [comment]
@peyang-Celeronのコミットによって主なコードスタイルが崩壊し、コミットを bc5c641b3bdcdce45714b4bd61d5ff48b9f64fa0 まで戻したため、Issueを再オープンします。このIssueの修正は以降私により行います。
